baseURL = "https://tangxin.fun/"
disqusShortname = ""
languageCode = "zh-cn"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "唐心's博客"
[[menu.footer]]
name = "YaYi"
url = "https://yayi.site"
weight = 3
[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
name = "Netlify"
parent = "Admin"
url = "admin"
weight = 1
[[menu.main]]
name = "Forestry"
parent = "Admin"
url = "admin/forestry"
weight = 2
[[menu.main]]
hasChildren = true
name = "Admin"
weight = 2
[[menu.main]]
URL = "tools"
name = "tools"
weight = 4
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3
[[menu.main]]
URL = "posts"
name = "Blog"
weight = 1
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "TangXin"
contact_form_action = "#"
copyright = "&copy; 2021 [TangXin](https://TangxinGH.github.com) All Rights Reserved"
description = "This is meta description"
google_tag_manager = ""
home = "Home"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, I'm  Tang Xin. <br> I help people make the  worlds best software"
[params.cookies]
enable = true
expire_days = 2
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = true
image = "images/hugo-muscot.svg"
title = "Get the best blog templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://yayi.site/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
