DefaultContentLanguage = "zh-cn"
author = "唐心"
baseURL = "https://blog.yayi.site/"
copyright = "Copyright © 2008–2019"
disqusShortname = "tangxin"  # Enable Disqus
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

googleAnalytics = "UA-FAKE"

hasCJKLanguage = true
languageCode = "zh-cn"
#themes = ["anatole", "iris", "northendlab-hugo", "tokiwa"]
theme = "tokiwa"
title = "唐心's博客"

#----以上是公有的

#anotole主题特有的

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


#iris 主题有的
canonifyURLs: true

#iris end

 

[params]
bannerFont = "fonts/exampleFont" 
description = "Tokiwa-iro is the theme color of this site." 
env = "production" # for Google Analytics and DISQUS.
 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = true 

# anotole的参数
 
title = "I'm tang xin"
author = "tang xin"
 
