DefaultContentLanguage = "zh-cn"
author = "唐心"
baseURL = "https://blog.yayi.site/"
copyright = "Copyright © 2008–2019"
disqusShortname = "tangxin"  # Enable Disqus
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

googleAnalytics = "UA-FAKE"

hasCJKLanguage = true
languageCode = "zh-cn"
#themes = ["anatole", "iris", "northendlab-hugo", "tokiwa"]
theme = "tokiwa"
title = "唐心's博客"

#----以上是公有的

#anotole主题特有的

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


#iris 主题有的
canonifyURLs: true

#iris end

#[markup]
#[markup.highlight]
#style = "monokailight"

#[markup.goldmark.renderer]
#unsafe = true

[params]
bannerFont = "fonts/exampleFont" 
description = "Tokiwa-iro is the theme color of this site." 
env = "production" # for Google Analytics and DISQUS.
 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTEX$
useChineseFonts = true 


[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
 [[menu.main]]
  name = "Contact"
  weight = 4
  identifier = "contact"
  url = "/contact/"
  
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2
  
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
bilibili = "http://bilibili.com/"
github = "http://github.com/tangxingh"
gitlab = "http://gitlab.com/"
instagram = "http://example.com/"
mail = "mailto:anon@example.com"
twitter = "http://twitter.com/"
weibo = "http://example.com/"
youtube = "http://youtube.com/"
zhihu = "http://example.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]
