DefaultContentLanguage = "zh-cn"
author = "唐心"
baseURL = "https://hugo.tangxin.fun/"
copyright = "Copyright © 2008–2021"
disqusShortname = "tangxin"
 
hasCJKLanguage = true
languageCode = "en"
title = "唐心's博客"

# 在 [params] 下面的值将会构成模板里的 .Site.Params 变量：
 
 
# 指向配置文件 
config = "config/configtokiwa.toml"
metaDataFormat = "toml"