backend:
  name: git-gateway
  repo: TangxinGH/netlify
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    description: >
      The description is a great place for tone setting写博客,
    folder: 'content'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    editor:
      preview: false
    view_filters:
      - label: Posts With Index
        field: title
        pattern: 'This is post #'
      - label: Posts Without Index
        field: title
        pattern: 'test'
      - label: Drafts
        field: draft
        pattern: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Cover Image', name: 'image',  widget: 'image', required: false, tagname: '' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }

  - name: 'configfile' # Used in routes, ie.: /admin/collections/:slug/edit
    label: '配置' # Used in the UI
    folder: 'config/_default'
    delete: false
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    file: 'config.toml'
    description: '不可能的'
    fields: # The fields each document in this collection have
      - { label: 'edit file', name: 'configtoml', widget: 'text' }
       

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: '_data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - label: 'Post Settings'
            name: posts
            widget: 'object'
            fields:
              - {
                  label: 'Number of posts on frontpage',
                  name: front_limit,
                  widget: number,
                  min: 1,
                  max: 10,
                }
              - { label: 'Default Author', name: author, widget: string }
              - {
                  label: 'Default Thumbnail',
                  name: thumb,
                  widget: image,
                  class: 'thumb',
                  required: false,
                }

      - name: 'authors'
        label: 'Authors'
        file: '_data/authors.yml'
        description: 'Author descriptions'
        fields:
          - name: authors
            label: Authors
            label_singular: 'Author'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string', hint: 'First and Last' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
    